### PR TITLE
Fix UNIX file permissions

### LINKED ISSUE #100: File hasn't read access after unpacking
I use `zip_entry_write` to write data to archive. Such unpacked file has no any access. On Linux it's a problem when working in console. So need a way to manually set `zip->entry.external_attr`.

### PR DESCRIPTION
**Pull request by drizt**
Need to explicity set UNIX file permissions when commpressing buffer
to entry. Without it later unpacked file can't be opened.

Fix #100

### CODE REVIEW

File: src/zip.c [hunk 1]
```diff
@@ -450,6 +450,14 @@ int zip_entry_close(struct zip_t *zip) {
     goto cleanup;
   }
 
+  // UNIX
+#if MZ_PLATFORM == 3
```
Comment (kuba--) [inline src/zip.c]: It makes sense to have a default permission mode for entries, but:
- would be good to set it up also for other platforms (if it's doable)
- `zip_entry_close` is not a right place because it will overwrite what was set by `zip_entry_fwrite`

**Comment by kuba--** [comment]
Also we need some test for that.

File: src/zip.c (hunk 1 above)
Comment (drizt) [reply src/zip.c]: It wont overwrite becouse it check current external attrs value and on UNIX for files it never will be zero.

Comment (kuba--) [reply src/zip.c]: so maybe it makes sense to set up the default value in zip_entry_open

Comment (drizt) [reply src/zip.c]: I agree.

Comment (drizt) [reply src/zip.c]: Add a test. Unsure I can't find how to check for `#if MZ_PLATFORM == 3` in test.c. My current `#ifdef __unix__` is not correct.

Comment (drizt) [reply src/zip.c]: Changed. Added macOS support. I tested both OS: Linux and macOS.

Comment (drizt) [reply src/zip.c]: Add a test. Unsure I can't find how to check for `#if MZ_PLATFORM == 3` in test.c. My current `#ifdef __unix__` is not correct.

File: src/zip.c [hunk 2]
```diff
@@ -277,7 +277,14 @@ int zip_entry_open(struct zip_t *zip, const char *entryname) {
   zip->entry.header_offset = zip->archive.m_archive_size;
   memset(zip->entry.header, 0, MZ_ZIP_LOCAL_DIR_HEADER_SIZE * sizeof(mz_uint8));
   zip->entry.method = 0;
+
+  // UNIX or APPLE
+#if MZ_PLATFORM == 3 || MZ_PLATFORM == 19
```
Comment (kuba--) [inline src/zip.c]: maybe make it compatible with what we have in read and extract, where on windows _do nothing_ else:
`(mz_uint32)((0100644 & 0xFFFF) << 16);`

Comment (drizt) [reply src/zip.c]: Yes.
